name: main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CentOS7
        uses: docker/build-push-action@v2.4.0
        with:
          file: Dockerfile.7
  push:
    needs: [ test ]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: gucchisk
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Publish CentOS7
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: gucchisk/centos7:homebrew
          file: Dockerfile.7
